services:
  postgres:
    image: postgres:16-alpine
    container_name: lab4-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - lab4_postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  users-api:
    image: ghcr.io/baykushevi/devops-labs/users-api:${APP_TAG:-latest}
    container_name: lab4-users-api
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DB_HOST: lab4-postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8081:5000"

  tasks-api:
    image: ghcr.io/baykushevi/devops-labs/tasks-api:${APP_TAG:-latest}
    container_name: lab4-tasks-api
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DB_HOST: lab4-postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8082:5000"

  adminer:
    image: adminer:latest
    container_name: lab4-adminer
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "${ADMINER_PORT:-8084}:8080"

volumes:
  lab4_postgres_data:

