services:
  postgres:
    image: postgres:16-alpine
    container_name: lab4-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - lab4_postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  users-api:
    build:
      context: .
      dockerfile: Dockerfile.users
      args:
        - APP_VERSION=${APP_VERSION}
        - GIT_COMMIT=${GIT_COMMIT}
    container_name: lab4-users-api
    restart: unless-stopped
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - APP_VERSION=${APP_VERSION}
      - GIT_COMMIT=${GIT_COMMIT}
      - BACKEND_PORT=${BACKEND_USERS_PORT}
    depends_on:
      - postgres
    ports:
      - "${BACKEND_USERS_HOST_PORT}:5000"

  tasks-api:
    build:
      context: .
      dockerfile: Dockerfile.tasks
      args:
        - APP_VERSION=${APP_VERSION}
        - GIT_COMMIT=${GIT_COMMIT}
    container_name: lab4-tasks-api
    restart: unless-stopped
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - APP_VERSION=${APP_VERSION}
      - GIT_COMMIT=${GIT_COMMIT}
      - BACKEND_PORT=${BACKEND_TASKS_PORT}
    depends_on:
      - postgres
    ports:
      - "${BACKEND_TASKS_HOST_PORT}:5000"

  adminer:
    image: adminer:latest
    container_name: lab4-adminer
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "${ADMINER_PORT}:8080"

volumes:
  lab4_postgres_data:

