global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "users-api"
    static_configs:
      - targets:
          - "192.168.68.116:8081"

  - job_name: "tasks-api"
    static_configs:
      - targets:
          - "192.168.68.116:8082"

  - job_name: "node-exporter"
    static_configs:
      - targets:
          - "192.168.68.116:9100"

  - job_name: "cadvisor"
    static_configs:
      - targets:
          - "192.168.68.116:8080"
